### ISSUE TITLE
Add Implementation of NAFNet: Nonlinear Activation Free Network for Image Restoration

### ISSUE THREAD

**Issue by soumik12345** [TrystAI/restorers#24]
Add implementation of **NAFNet: Nonlinear Activation Free Network for Image Restoration** as proposed by the paper [**Simple Baselines for Image Restoration**](https://arxiv.org/abs/2204.04676) from ECCV 2022.

Official PyTorch Implementation: https://github.com/megvii-research/NAFNet

**Comment by Samarendra109** [comment]
I want to take this issue up

**Comment by soumik12345** [comment]
> I want to take this issue up

cc: @ariG23498 @SauravMaheshkar

**Comment by soumik12345** [comment]
Reopening the issue since the model has not yet been added.

**Comment by soumik12345** [comment]
@Samarendra109 Since I was unable to review https://github.com/soumik12345/restorers/pull/36, I'll add some of my reviews here. For any change requests I make here, please add them as part of https://github.com/soumik12345/restorers/pull/39.

- https://github.com/soumik12345/restorers/blob/main/restorers/model/nafnet/nafnet.py#L9-L27
  - Nice!!!
  - [ ] Please update the docstring for this class like you did [here](https://github.com/soumik12345/restorers/blob/main/restorers/model/nafnet/nafnet.py#L31-L53).
- These lines are not necessary:
  - [ ] https://github.com/soumik12345/restorers/blob/main/restorers/model/nafnet/nafblock.py#L88
  - [ ] https://github.com/soumik12345/restorers/blob/main/restorers/model/nafnet/nafblock.py#L89
  - [ ] https://github.com/soumik12345/restorers/blob/main/restorers/model/nafnet/nafblock.py#L92
  - [ ] https://github.com/soumik12345/restorers/blob/main/restorers/model/nafnet/nafblock.py#L94
  - [ ] https://github.com/soumik12345/restorers/blob/main/restorers/model/nafnet/nafblock.py#L100
  - [ ] https://github.com/soumik12345/restorers/blob/main/restorers/model/nafnet/nafblock.py#L101
  - [ ] https://github.com/soumik12345/restorers/blob/main/restorers/model/nafnet/nafblock.py#L105
  - [ ] https://github.com/soumik12345/restorers/blob/main/restorers/model/nafnet/nafblock.py#L106
- https://github.com/soumik12345/restorers/blob/main/restorers/model/nafnet/nafblock.py#L134-L139
  - Nice!!!

**Comment by Samarendra109** [comment]
@soumik12345 did all the changes as requested.
