### ISSUE TITLE
docs: Fill in missing Doctrings for models

### ISSUE THREAD

**Issue by soumik12345** [TrystAI/restorers#61]
## Action Items

- [x] Add references to the doctrings for [`SimpleGate`](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafblock.py#L11).
- [x] Elaborate docstrings for [`ChannelAttention`](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafblock.py#L37) with references and more details.
- [x] Elaborate docstrings for [`SimplifiedChannelAttention`](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafblock.py#L71) with references and more details.
- [x] Elaborate docstrings for [`NAFBlock`](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafblock.py#L100) with references and more details.
- [x] Add references and parameters to the docstrings for [`PixelShuffle`](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafnet.py#L10).
- [x] Add references and parameters to the docstrings for [`UpScale`](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafnet.py#L39).
- [x] Add references to the docstrings for [`NAFNet`](https://github.com/TrystAI/restorers/blob/main/restorers/model/nafnet/nafnet.py#L85).

**Comment by Samarendra109** [comment]
UpScale is just a convenience class that I had added. It uses pixelshuffle only. The authors of the original paper has used pytorch sequential module instead. I don't think we need to add reference for that block.
